Develop
B-Tshehla/credit_conveyor_application pull request #2
Opened 2022-10-17 10:43 UTC by B-Tshehla

2022-10-17 18:13 UTC, MichaelDeyev commented on conveyor/src/main/java/com/enfint/conveyor/controller/ConveyorController.java
> +    ScoringDataDTO scoringDataDTO;
This field should not be a global-field.

2022-10-17 18:13 UTC, MichaelDeyev commented on conveyor/src/main/java/com/enfint/conveyor/controller/ConveyorController.java
> +@RequestMapping("conveyor")
add "/" in the begining of the path

2022-10-17 18:13 UTC, MichaelDeyev commented on conveyor/src/main/java/com/enfint/conveyor/Main.java
> +    }
it would be better if this bean-defenition will be located in separate class, marked @Configuration

2022-10-17 18:13 UTC, MichaelDeyev commented on conveyor/src/main/java/com/enfint/conveyor/service/OffersConveyorService.java
> +import com.enfint.conveyor.dto.*;
it is a bad way to use * in imports.

2022-10-17 18:13 UTC, MichaelDeyev commented on conveyor/src/main/java/com/enfint/conveyor/service/ScoringConveyorService.java
> +        }
maybe you can rewrite this for-loop using StreamAPI?

2022-10-25 11:04 UTC, MichaelDeyev requested changes

2022-10-25 11:04 UTC, MichaelDeyev commented on conveyor/src/main/java/com/enfint/conveyor/Main.java
> +    private static final Logger log = LoggerFactory.getLogger(Main.class);
you don't need to use logger in your main-class.

2022-10-25 11:04 UTC, MichaelDeyev commented on conveyor/src/main/java/com/enfint/conveyor/controller/ConveyorController.java
> +    private final Logger log = LoggerFactory.getLogger(ConveyorController.class);
use `@Slf4j` annotation instead of defining logger explicitly

2022-10-25 11:04 UTC, MichaelDeyev commented on conveyor/src/main/java/com/enfint/conveyor/controller/ConveyorController.java
> +        log.info("************ Getting Loan offers ***************");
You should pass method's argument into logger message 
example `log.info("Getting Loan offers loanApplicationRequest = {}", loanApplicationRequest);`

2022-10-25 11:04 UTC, MichaelDeyev commented on conveyor/src/main/java/com/enfint/conveyor/Main.java
> +@RequiredArgsConstructor
You don't need this annotation here, beacause you did't inject any dependency

2022-10-25 11:04 UTC, MichaelDeyev commented on conveyor/src/main/java/com/enfint/conveyor/exception/Refusal.java
> +    }
Use `@RequiredArgsConstructor`

2022-10-25 11:04 UTC, MichaelDeyev commented on conveyor/src/main/java/com/enfint/conveyor/service/CalculateFullRatingService.java
> +            log.info("Married rate {}",rate);
fix formatting, please. Use ctrl+alt+L hotkey

2022-10-25 11:04 UTC, MichaelDeyev commented on conveyor/src/main/java/com/enfint/conveyor/service/OffersConveyorService.java
> +
formatting

2022-10-25 11:04 UTC, MichaelDeyev commented on conveyor/src/main/java/com/enfint/conveyor/service/OffersConveyorService.java
> +        this.offerCalculate = offerCalculate;
Use `@RequiredArgsConstructor`

2022-10-25 11:04 UTC, MichaelDeyev commented on conveyor/src/test/java/com/enfint/conveyor/service/CalculateFullRatingServiceTest.java
> +@RequiredArgsConstructor
you don't need this annotation here

2022-10-25 11:04 UTC, MichaelDeyev commented on conveyor/src/test/java/com/enfint/conveyor/service/OffersConveyorServiceTest.java
> +@RequiredArgsConstructor
remove this annotation

2022-10-25 11:04 UTC, MichaelDeyev commented on conveyor/src/test/java/com/enfint/conveyor/service/OfferCalculationServiceTest.java
> +
use `@SpringBootTest` annotation

2022-10-25 14:24 UTC, B-Tshehla commented on conveyor/src/main/java/com/enfint/conveyor/service/OffersConveyorService.java
> +        this.offerCalculate = offerCalculate;
When I don't have that constructor there the test file fails to compile

2022-10-25 14:28 UTC, B-Tshehla commented on conveyor/src/main/java/com/enfint/conveyor/service/OffersConveyorService.java
> +        this.offerCalculate = offerCalculate;
when I remove the constructor the OfferConveyorserviceTest does not compile. It has errors

2022-10-27 08:17 UTC, MichaelDeyev commented on conveyor/src/main/java/com/enfint/conveyor/exception/Refusal.java
> +@RequiredArgsConstructor
This is the data-class. Use `@Data` annotation instead of @RequiredArgsConstructor

2022-10-27 08:17 UTC, MichaelDeyev commented on conveyor/src/main/java/com/enfint/conveyor/exception/Refusal.java
> +    private final String message;
remove `final`

2022-10-27 08:17 UTC, MichaelDeyev commented on conveyor/src/main/java/com/enfint/conveyor/exception/Refusal.java
> +        return timestamp;
getters will generate by `@Data`

2022-10-27 08:17 UTC, MichaelDeyev commented on conveyor/src/main/java/com/enfint/conveyor/service/CalculateFullRatingService.java
> +@NoArgsConstructor
No-args constructor creates by default, so you don't need to use this annotation

2022-10-27 08:17 UTC, MichaelDeyev commented on conveyor/src/test/java/com/enfint/conveyor/controller/ConveyorControllerTest.java
> +        assert loanOfferList != null;
use `assertNotNull` static method

2022-10-27 08:17 UTC, MichaelDeyev commented on conveyor/src/test/java/com/enfint/conveyor/controller/ConveyorControllerTest.java
> +    void shouldGetAListWithFourLoanOffers() {
add public modificator to all test-methods

2022-10-27 08:17 UTC, MichaelDeyev commented on conveyor/src/test/java/com/enfint/conveyor/controller/ConveyorControllerTest.java
> +        assert credit != null;
use `assertNotNull` static method

2022-10-27 08:17 UTC, MichaelDeyev commented on conveyor/src/test/java/com/enfint/conveyor/service/OfferCalculationServiceTest.java
> +class OfferCalculationServiceTest {
use `@ExtedsWith(MockitoExtention.class)`

2022-10-27 08:17 UTC, MichaelDeyev commented on conveyor/src/test/java/com/enfint/conveyor/service/OfferCalculationServiceTest.java
> +    OfferCalculationService underTest;
Use @InjectMocks Annotation and remove definition of this service

2022-10-27 08:17 UTC, MichaelDeyev commented on conveyor/src/test/java/com/enfint/conveyor/service/OffersConveyorServiceTest.java
> +    private OffersConveyorService underTest;
`@InjectMocks` here

2022-10-27 08:17 UTC, MichaelDeyev commented on conveyor/src/test/java/com/enfint/conveyor/service/OffersConveyorServiceTest.java
> +    private static OfferCalculationService offerCalculationService;
remove static and put `@Mock`

2022-10-27 08:17 UTC, MichaelDeyev commented on conveyor/src/test/java/com/enfint/conveyor/service/OffersConveyorServiceTest.java
> +    private LoanApplicationRequestDTO loanApplicationRequest;
add `@Mock`

2022-10-27 08:17 UTC, MichaelDeyev commented on conveyor/src/test/java/com/enfint/conveyor/service/OffersConveyorServiceTest.java
> +class OffersConveyorServiceTest {
use `@ExtedsWith(MockitoExtention.class)` to enable mocking

2022-10-27 08:17 UTC, MichaelDeyev commented on conveyor/src/test/java/com/enfint/conveyor/service/ScoringConveyorServiceTest.java
> +class ScoringConveyorServiceTest {
see comments from OffersConveyorServiceTest

2022-10-28 14:30 UTC, MichaelDeyev approved these changes
👍🏼

2022-10-29 11:02 UTC, merged